version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///app/db.sqlite3  # Utilisation de SQLite
    volumes:
      - ./backend:/app  # Monte le code source
      - ./backend/db.sqlite3:/app/db.sqlite3  # Persistance de la base de données
      - shared_data:/app/shared  # Répertoire partagé avec le frontend
    command: bash -c "pip install --no-cache-dir -r requirements.txt && python app.py"  # Commande à exécuter dans le backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Évite les conflits de node_modules
      - shared_data:/app/shared  # Répertoire partagé avec le backend
    command: streamlit run app.py 

volumes:
  backend_data:
  shared_data:  # Volume partagé entre frontend et backend
